name: Publish rich-click to PyPI
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    if: github.repository == 'ewels/rich-click'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install python dependencies
        run: python -m pip install --upgrade pip setuptools wheel build

      - name: Build the distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
