name: Rich-codex
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  rich_codex:
    if: github.repository_owner == 'ewels' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3

      - name: Install your custom tools
        run: pip install ".[dev]"

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          use_uv: "true"
          skip_python_setup: "true"
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg
          terminal_width: 80
          skip_git_checks: "true"
          working_dir: "."
